function y = weight_k(kps,G,v,natm,nx_sc,ny_sc,nz_sc,pos_sc,pos)
    y = 0;
    y3 = zeros(natm*3,1);
    for ii = 1:natm
        for jj = 1:3
            for i = 1:nx_sc
                for j = 1:ny_sc
                    for k = 1:nz_sc
                        y3(3*(ii-1)+jj) = y3(3*(ii-1)+jj)...
                        + v((i-1)*ny_sc*nz_sc*natm*3 ...
                           +(j-1)*nz_sc*natm*3 ...
                           +(k-1)*natm*3 ...
                           +(ii-1)*3+jj) ...
                           *exp(-1j*dot( ...
                           pos_sc((i-1)*ny_sc*nz_sc*natm ...
                           +(j-1)*nz_sc*natm ...
                           +(k-1)*natm+ii,:)...
                            -pos(ii,:),G+kps)); %
                    end
                end
            end
        end
    end
    y = dot(y3,y3)/(nx_sc*ny_sc*nz_sc);
end